[2023-10-05 19:34:12,252] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_increment scheduled__2023-09-27T19:32:37.598184+00:00 [queued]>
[2023-10-05 19:34:12,269] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_increment scheduled__2023-09-27T19:32:37.598184+00:00 [queued]>
[2023-10-05 19:34:12,270] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:34:12,270] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-05 19:34:12,271] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:34:12,298] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_increment> on 2023-09-27 19:32:37.598184+00:00
[2023-10-05 19:34:12,303] {standard_task_runner.py:52} INFO - Started process 962 to run task
[2023-10-05 19:34:12,307] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'get_increment', 'scheduled__2023-09-27T19:32:37.598184+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmptn5h7rre', '--error-file', '/tmp/tmpinl3n7dt']
[2023-10-05 19:34:12,308] {standard_task_runner.py:80} INFO - Job 10: Subtask get_increment
[2023-10-05 19:34:12,385] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.get_increment scheduled__2023-09-27T19:32:37.598184+00:00 [running]> on host 8305c4468fa5
[2023-10-05 19:34:12,473] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=get_increment
AIRFLOW_CTX_EXECUTION_DATE=2023-09-27T19:32:37.598184+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-27T19:32:37.598184+00:00
[2023-10-05 19:34:12,474] {logging_mixin.py:115} INFO - Making request get_increment
[2023-10-05 19:34:12,640] {logging_mixin.py:115} INFO - Response is b'{"report_id":"TWpBeU15MHhNQzB3TlZReE9Ub3pNam8wT1Fsc2EyNWZjRzl3YjNZPQ==","date":"2023-09-27 00:00:00","status":"NOT FOUND","data":{"increment_id":null},"debug_info":"Date is too early. You need specify the date greater then date in the general report."}'
[2023-10-05 19:34:12,643] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/lessons/dags/sprint3.py", line 76, in get_increment
    raise ValueError(f'Increment is empty. Most probably due to error in API call.')
ValueError: Increment is empty. Most probably due to error in API call.
[2023-10-05 19:34:12,676] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=get_increment, execution_date=20230927T193237, start_date=20231005T193412, end_date=20231005T193412
[2023-10-05 19:34:12,697] {standard_task_runner.py:92} ERROR - Failed to execute job 10 for task get_increment (Increment is empty. Most probably due to error in API call.; 962)
[2023-10-05 19:34:12,722] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-05 19:34:12,799] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
