[2023-10-07 12:52:40,195] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_f_customer_retention manual__2023-10-07T12:51:19.432801+00:00 [queued]>
[2023-10-07 12:52:40,202] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_f_customer_retention manual__2023-10-07T12:51:19.432801+00:00 [queued]>
[2023-10-07 12:52:40,202] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 12:52:40,203] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-07 12:52:40,203] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 12:52:40,211] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_f_customer_retention> on 2023-10-07 12:51:19.432801+00:00
[2023-10-07 12:52:40,214] {standard_task_runner.py:52} INFO - Started process 3595 to run task
[2023-10-07 12:52:40,215] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'update_f_customer_retention', 'manual__2023-10-07T12:51:19.432801+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmpabpa517z', '--error-file', '/tmp/tmppy34zipf']
[2023-10-07 12:52:40,216] {standard_task_runner.py:80} INFO - Job 99: Subtask update_f_customer_retention
[2023-10-07 12:52:40,255] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.update_f_customer_retention manual__2023-10-07T12:51:19.432801+00:00 [running]> on host d964b2b568e5
[2023-10-07 12:52:40,299] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=update_f_customer_retention
AIRFLOW_CTX_EXECUTION_DATE=2023-10-07T12:51:19.432801+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-07T12:51:19.432801+00:00
[2023-10-07 12:52:40,308] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2023-10-07 12:52:40,313] {sql.py:315} INFO - Running statement: delete from mart.f_customer_retention r
where r.period_id in(
    select
        dc.first_day_of_week
    from mart.d_calendar dc
    where dc.date_actual::date = '2023-10-07'
);

insert into mart.f_customer_retention(
    period_name 
    ,period_id 
    ,item_id 
    ,new_customers_count 
    ,returning_customers_count
    ,refunded_customer_count 
    ,new_customers_revenue 
    ,returning_customers_revenue 
    ,customers_refunded  
)

select
    'weekly' as period_name 
    ,t.period_id 
    ,t.item_id 
    ,t.new_customers_count 
    ,t.returning_customers_count
    ,t.refunded_customer_count 
    ,t.new_customers_revenue 
    ,t.returning_customers_revenue 
    ,t.customers_refunded 
from(
    select
        --'weekly' as period_name
        q.period_id
        ,q.item_id
        ,sum(case when cnt_sales = 1 then 1 else 0 end) as new_customers_count
        ,sum(case when cnt_sales > 1 then 1 else 0 end) as returning_customers_count
        ,sum(case when cnt_rej >= 1 then 1 else 0 end) as refunded_customer_count
        ,sum(case when cnt_sales = 1 then payment_amount else 0 end ) as new_customers_revenue
        ,sum(case when cnt_sales > 1 then payment_amount else 0 end ) as returning_customers_revenue
        ,sum(cnt_rej) as customers_refunded
    from(
        select
            dc.first_day_of_week as period_id
            ,fs.item_id
            ,fs.customer_id
            ,count(*) as cnt_sales
            ,sum(
                case
                    when fs.status = 'refunded' then 1
                    else 0
                end
            ) as cnt_rej
            ,sum(payment_amount) as payment_amount
        from mart.f_sales fs  
        inner join mart.d_calendar dc on fs.date_id = dc.date_id
        where dc.date_actual::date = '2023-10-07' 
        group by dc.first_day_of_week
                ,fs.item_id
                ,fs.customer_id
    ) q
    group by q.period_id
            ,q.item_id
) t , parameters: {'date': ('{{ ds }}',)}
[2023-10-07 12:52:40,315] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/usr/local/lib/python3.8/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 318, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UndefinedFunction: operator does not exist: text = date
LINE 2: where r.period_id in(
                          ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[2023-10-07 12:52:40,323] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=update_f_customer_retention, execution_date=20231007T125119, start_date=20231007T125240, end_date=20231007T125240
[2023-10-07 12:52:40,330] {standard_task_runner.py:92} ERROR - Failed to execute job 99 for task update_f_customer_retention (operator does not exist: text = date
LINE 2: where r.period_id in(
                          ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
; 3595)
[2023-10-07 12:52:40,349] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-07 12:52:40,371] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
