[2023-10-05 19:18:59,724] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_increment manual__2023-10-05T19:17:43.581273+00:00 [queued]>
[2023-10-05 19:18:59,736] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_increment manual__2023-10-05T19:17:43.581273+00:00 [queued]>
[2023-10-05 19:18:59,737] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:18:59,738] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-05 19:18:59,738] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:18:59,753] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_increment> on 2023-10-05 19:17:43.581273+00:00
[2023-10-05 19:18:59,756] {standard_task_runner.py:52} INFO - Started process 3065 to run task
[2023-10-05 19:18:59,759] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'get_increment', 'manual__2023-10-05T19:17:43.581273+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmpz9wi22vc', '--error-file', '/tmp/tmpzglls0_1']
[2023-10-05 19:18:59,761] {standard_task_runner.py:80} INFO - Job 46: Subtask get_increment
[2023-10-05 19:18:59,819] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.get_increment manual__2023-10-05T19:17:43.581273+00:00 [running]> on host 2026d982a63a
[2023-10-05 19:18:59,891] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=get_increment
AIRFLOW_CTX_EXECUTION_DATE=2023-10-05T19:17:43.581273+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-05T19:17:43.581273+00:00
[2023-10-05 19:18:59,892] {logging_mixin.py:115} INFO - Making request get_increment
[2023-10-05 19:19:00,222] {logging_mixin.py:115} INFO - Response is b'{"report_id":"TWpBeU15MHhNQzB3TlZReE9Ub3hOem8wTndsc2EyNWZjRzl3YjNZPQ==","date":"2023-10-05 00:00:00","status":"NOT FOUND","data":{"increment_id":null}}'
[2023-10-05 19:19:00,223] {logging_mixin.py:115} INFO - b'{"report_id":"TWpBeU15MHhNQzB3TlZReE9Ub3hOem8wTndsc2EyNWZjRzl3YjNZPQ==","date":"2023-10-05 00:00:00","status":"NOT FOUND","data":{"increment_id":null}}'
[2023-10-05 19:19:00,224] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/lessons/dags/sprint3.py", line 77, in get_increment
    raise ValueError(f'Increment is empty. Most probably due to error in API call.')
ValueError: Increment is empty. Most probably due to error in API call.
[2023-10-05 19:19:00,241] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=get_increment, execution_date=20231005T191743, start_date=20231005T191859, end_date=20231005T191900
[2023-10-05 19:19:00,258] {standard_task_runner.py:92} ERROR - Failed to execute job 46 for task get_increment (Increment is empty. Most probably due to error in API call.; 3065)
[2023-10-05 19:19:00,294] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-05 19:19:00,371] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
